#!/usr/bin/env python3
"""bdf2c.py — BDF bitmap font -> a flat C glyph table.

    ./tools/bdf2c.py Tamzen6x12r.bdf font6x12.c font6x12 6 12

Deliberately NOT an lv_font_t. The terminal blitter draws fixed-size cells and
needs no metrics, kerning, cmap lookup or LVGL runtime -- it indexes
glyphs[cp-0x20][row] and shifts out bits. That keeps the renderer independent of
LVGL (which is suspended while the terminal owns the panel) and makes the table
a plain const array in flash.

Output convention matches tamzen8x16.c: one byte per scanline, MSB = leftmost
pixel, so a 6px-wide glyph uses bits 7..2 and leaves bits 1..0 clear.
"""

import sys


def parse_bdf(path):
    """Return (fbb, glyphs) where glyphs maps codepoint -> (bbx, rows)."""
    fbb = None
    glyphs = {}
    cp = None
    bbx = None
    rows = None
    in_bitmap = False

    with open(path, "r", errors="replace") as fh:
        for line in fh:
            parts = line.split()
            if not parts:
                continue
            key = parts[0]

            if key == "FONTBOUNDINGBOX":
                fbb = tuple(int(x) for x in parts[1:5])       # w h xoff yoff
            elif key == "STARTCHAR":
                cp, bbx, rows, in_bitmap = None, None, [], False
            elif key == "ENCODING":
                cp = int(parts[1])
            elif key == "BBX":
                bbx = tuple(int(x) for x in parts[1:5])
            elif key == "BITMAP":
                in_bitmap = True
            elif key == "ENDCHAR":
                if cp is not None and bbx is not None:
                    glyphs[cp] = (bbx, rows)
                cp, bbx, rows, in_bitmap = None, None, [], False
            elif in_bitmap:
                rows.append(parts[0])

    if fbb is None:
        raise SystemExit("no FONTBOUNDINGBOX in %s" % path)
    return fbb, glyphs


def render(fbb, bbx, hexrows, cw, ch):
    """Rasterise one glyph into `ch` bytes, MSB=leftmost, using BDF offsets."""
    out = [0] * ch
    if bbx is None:
        return out
    gw, gh, gx, gy = bbx
    # Ascent: rows above the baseline in the font's own box. Row 0 of our cell is
    # the TOP, so a glyph's first bitmap row lands at (ascent - gy - gh).
    ascent = fbb[1] + fbb[3]
    top = ascent - gy - gh

    for r, hexrow in enumerate(hexrows[:gh]):
        if not hexrow:
            continue
        val = int(hexrow, 16)
        nbits = len(hexrow) * 4            # BDF pads each row to whole bytes
        cell_row = top + r
        if cell_row < 0 or cell_row >= ch:
            continue                        # glyph taller than the cell: clip
        byte = 0
        for c in range(gw):
            bit = (val >> (nbits - 1 - c)) & 1
            if not bit:
                continue
            col = gx + c
            if 0 <= col < cw:
                byte |= 1 << (7 - col)      # MSB = leftmost, same as tamzen8x16
        out[cell_row] = byte
    return out


def main():
    if len(sys.argv) != 6:
        raise SystemExit(__doc__)
    src, dst, name, cw, ch = sys.argv[1], sys.argv[2], sys.argv[3], int(sys.argv[4]), int(sys.argv[5])

    fbb, glyphs = parse_bdf(src)
    first, last = 0x20, 0x7E
    missing = [cp for cp in range(first, last + 1) if cp not in glyphs]

    lines = []
    lines.append("// Generated by tools/bdf2c.py from %s -- do not edit by hand." % src.split("/")[-1])
    lines.append("//")
    lines.append("// %dx%d monospace glyphs, ASCII 0x%02X..0x%02X. One byte per scanline," % (cw, ch, first, last))
    lines.append("// MSB = leftmost pixel (bits 7..%d used), same convention as tamzen8x16.c." % (8 - cw))
    lines.append("// A flat table, NOT an lv_font_t: the terminal blitter indexes")
    lines.append("// %s[cp - 0x%02X][row] directly and needs no LVGL runtime." % (name, first))
    lines.append("//")
    lines.append("// Tamzen is derived from Tamsyn (permissive); see the upstream font for")
    lines.append("// its licence: github.com/sunaku/tamzen-font")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("const uint8_t %s[%d][%d] = {" % (name, last - first + 1, ch))

    for cp in range(first, last + 1):
        bbx, hexrows = glyphs.get(cp, (None, []))
        bits = render(fbb, bbx, hexrows, cw, ch)
        body = ", ".join("0x%02X" % b for b in bits)
        ch_disp = chr(cp) if cp != 0x5C else "\\\\"
        lines.append("\t/* 0x%02X %-3s */ { %s }," % (cp, "'%s'" % ch_disp, body))

    lines.append("};")
    lines.append("")

    with open(dst, "w") as fh:
        fh.write("\n".join(lines))

    print("wrote %s: %d glyphs, %d bytes of table" % (dst, last - first + 1, (last - first + 1) * ch))
    if missing:
        print("WARNING: %d codepoints missing from the BDF, emitted blank: %s"
              % (len(missing), " ".join("0x%02X" % c for c in missing)))


if __name__ == "__main__":
    main()


# ---------------------------------------------------------------------------
# Box-drawing glyphs are GENERATED, not sourced from a font.
#
# At 6x12 the only thing that matters is that adjacent cells JOIN: a horizontal
# must span all 6 columns and a vertical all 12 rows, or the frame comes out
# dashed. Generating guarantees that; a scavenged font would not.
#
# They occupy a private transmitted range 0x80.. (the DEC Special Graphics trick), so
# the protocol still carries one byte per cell.
